[package]
name = "flt-01"
version = "0.1.0"
edition = "2024"
authors = ["GOGIK <gogik.audio@gmail.com>"]
description = "GOGIK FLT-01 Module"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs", "standalone"] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git" }
gog_common = { git = "https://github.com/georgejawoods/GOG-COMMON.git" }

[[bin]]
name = "gog_flt_01_desktop"
path = "src/main.rs"

[build-dependencies]
winres = "0.1"

[workspace]
members = [
    "xtask",
]